# main.py
import os
import sys
import time
import signal

BANNER = r"""
\033[1;35m╔══════════════════════════════════════════════════════════════╗\033[0m
\033[1;36m║   CHIKATILO   MATRP   AND   RUAN    —    Forum Tracker Bot     ║\033[0m
\033[1;35m╚══════════════════════════════════════════════════════════════╝\033[0m
"""

CONFIG_TEMPLATE = '''# config.py autogenerated
VK_TOKEN = "{vk_token}"
XF_USER = "{xf_user}"
XF_SESSION = "{xf_session}"
XF_TFA_TRUST = "{xf_tfa_trust}"
FORUM_BASE = "https://forum.matrp.ru"
POLL_INTERVAL_SEC = {poll_interval}
ADMINS = "{admins}"
'''

def interactive_setup(path="config.py"):
    if os.path.exists(path):
        print(BANNER)
        print("Using existing config.py")
        return
    print(BANNER)
    print("Interactive setup - enter tokens/cookies (empty allowed).")
    vk = input("VK_TOKEN: ").strip()
    xf_user = input("XF_USER: ").strip()
    xf_session = input("XF_SESSION: ").strip()
    xf_tfa = input("XF_TFA_TRUST: ").strip()
    poll = input("POLL_INTERVAL_SEC (default 20): ").strip() or "20"
    admins = input("ADMINS (comma-separated user ids): ").strip()
    content = CONFIG_TEMPLATE.format(
        vk_token=vk.replace('"','\\"'),
        xf_user=xf_user.replace('"','\\"'),
        xf_session=xf_session.replace('"','\\"'),
        xf_tfa_trust=xf_tfa.replace('"','\\"'),
        poll_interval=poll,
        admins=admins.replace('"','\\"')
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("Saved config.py")

def main():
    interactive_setup("config.py")
    sys.path.insert(0, os.path.abspath("."))
    from bot.vk_bot import VKBot
    from bot.forum_tracker import ForumTracker

    vk = VKBot()
    tracker = ForumTracker(vk)

    def shutdown(sig, frame):
        print("Shutting down...")
        try: tracker.stop()
        except: pass
        try: vk.stop()
        except: pass
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    print(BANNER)
    print("Starting services...")
    vk.start()
    tracker.start()
    print("Bot running. Press Ctrl+C to stop.")
    while True:
        time.sleep(3600)

if __name__ == "__main__":
    main()
