# main.py
import os
import sys
import time
import signal
from colorama import Fore, Style, init

init(autoreset=True)

BANNER = r"""
╔════════════════════════════════════════════════════════════════════╗
║                                                                    ║
║   ███╗   ███╗ █████╗ ████████╗██████╗ ██████╗                     ║
║   ████╗ ████║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗                     ║
║   ██╔████╔██║███████║   ██║   ██████╔╝██████╔╝                     ║
║   ██║╚██╔╝██║██╔══██║   ██║   ██╔═══╝ ██╔══██╗                     ║
║   ██║ ╚═╝ ██║██║  ██║   ██║   ██║     ██║  ██║                     ║
║   ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝                     ║
║                                                                    ║
║          MATRP FORUM TRACKER — VK EDITION                           ║
╚════════════════════════════════════════════════════════════════════╝
"""

CONFIG_TEMPLATE = '''# config.py - autogenerated. Do NOT commit secrets to public repo.
VK_TOKEN = "{vk_token}"

# Forum cookies (XF)
XF_USER = "{xf_user}"
XF_SESSION = "{xf_session}"
XF_TFA_TRUST = "{xf_tfa_trust}"

FORUM_BASE = "https://forum.matrp.ru"
POLL_INTERVAL_SEC = {poll_interval}

# Optional: comma-separated admin user IDs (e.g. "12345,67890")
ADMINS = "{admins}"
'''


def interactive_setup(path="config.py"):
    if os.path.exists(path):
        print(Fore.GREEN + "config.py уже есть, пропускаем настройку." + Style.RESET_ALL)
        return
    print(BANNER)
    print(Fore.CYAN + "Первичная настройка бота — введите значения (пусто = оставит пустые строки)." + Style.RESET_ALL)
    vk_token = input("VK_TOKEN: ").strip()
    xf_user = input("XF_USER (cookie): ").strip()
    xf_session = input("XF_SESSION (cookie): ").strip()
    xf_tfa = input("XF_TFA_TRUST (cookie): ").strip()
    poll = input("POLL_INTERVAL_SEC (default 20): ").strip() or "20"
    admins = input("ADMINS (comma-separated user IDs, optional): ").strip()
    content = CONFIG_TEMPLATE.format(
        vk_token=vk_token.replace('"','\\"'),
        xf_user=xf_user.replace('"','\\"'),
        xf_session=xf_session.replace('"','\\"'),
        xf_tfa_trust=xf_tfa.replace('"','\\"'),
        poll_interval=poll,
        admins=admins.replace('"','\\"')
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(Fore.GREEN + "config.py создан. Перезапустите бота." + Style.RESET_ALL)
    sys.exit(0)


def main():
    interactive_setup("config.py")

    # добавляем текущую директорию для импорта bot
    sys.path.insert(0, os.path.abspath("."))

    from config import VK_TOKEN, XF_USER, XF_TFA_TRUST, XF_SESSION
    from bot.vk_bot import VKBot
    from bot.forum_tracker import ForumTracker

    vk = VKBot()
    tracker = ForumTracker(XF_USER, XF_TFA_TRUST, XF_SESSION, vk)

    def shutdown(signum, frame):
        print(Fore.RED + "\nSignal received, stopping..." + Style.RESET_ALL)
        try:
            tracker.stop()
        except Exception:
            pass
        try:
            vk.stop()
        except Exception:
            pass
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    print(BANNER)
    print(Fore.CYAN + "Запуск сервисов..." + Style.RESET_ALL)

    vk.start()        # запускаем longpoll в отдельном потоке
    tracker.start()   # запускаем форум-трекер в отдельном потоке

    print(Fore.GREEN + "Сервисы запущены. Бот работает." + Style.RESET_ALL)
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        shutdown(None, None)


if __name__ == "__main__":
    main()
